### ISSUE TITLE
QueryTools.stringify fails on null values

### ISSUE THREAD

**Issue by miwillhite** [ParsePlatform/ParseReact#66]
I have a field on my Parse model that has `null` as a value. This should be valid, but when it hits the `QueryTools.stringify` method I get the following error:

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at eval (eval at evaluate (unknown source), <anonymous>:1:8)
    at Object.InjectedScript._evaluateOn (<anonymous>:895:55)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:954:21)
    at stringify (http://localhost:4000/js/main.js:3687:3)
    at stringify (http://localhost:4000/js/main.js:3690:46)
    at Array.map (native)
    at stringify (http://localhost:4000/js/main.js:3682:23)
    ...
```

**Comment by andrewimm** [comment]
Thanks. Fixed, and added unit tests to cover this. I'll release v0.3.2 shortly.
